server:
  port: 8000

spring:
  application:
    name: ananops-provider-uac
  datasource:
    username: root
    password: 123456
  redis:
    database: 0
    host: ananops-db-redis
    port: 6379
#    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
logging:
  level:
    com.ananops.provider.mapper: debug
